name: Sync to Hugging Face Space

on:
  push:
    branches: [main]  # Runs when pushing to main branch

  workflow_dispatch:  # Allows manual triggering

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Full history
        lfs: false

    - name: Ignore Large Files
      run: |
        export FILTER_BRANCH_SQUELCH_WARNING=1
        git filter-branch --force --index-filter 'git rm -rf --cached --ignore-unmatch "Automated Code"' --prune-empty --tag-name-filter cat -- --all

    - name: Set Remote URL with Hugging Face Token
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN_BLOG_AI }}
      run: |
        git remote set-url origin https://neuralgeekroot:${HF_TOKEN}@huggingface.co/spaces/neuralgeekroot/AutomatedCodeReview.git

    - name: Push to Hugging Face Space
      run: |
        git push origin main --force
